### ISSUE TITLE
No DSD ppa for Ubuntu 20.4? 

### ISSUE THREAD

**Issue by ShaninAZ** [szechyjs/dsd#113]
This may not be the correct forum for this bug report (I'm new to having troubles with installing the ppa for DSD), so if incorrectly lodged, please let me know and point me to the right place.

I am attempting to get DSD up and running on a Ubuntu 20.4 desktop. In attempting to do so, I encountered the following:

debi http://ppa.launchpad.net/szechyjs/dsd/ubuntu 20.4 main
debi: warning:     debian/changelog(l12): found start of entry where expected more change data or trailer
LINE: sdrangel (6.7.0-1) unstable; urgency=medium
debi: warning:     debian/changelog(l12): found end of file where expected more change data or trailer
debi: can't read sdrangel_6.8.0-1_amd64.changes!

This seems to be an issue only for Ubuntu 20.4, if I understand the issue correctly. Can a Ubuntu 20.4 version be added to the repository, so that I can use this great module?

Many thanks, in advance!

**Comment by ShaninAZ** [comment]
BTW- I'm trying the Docker installation, and by following 

https://discourse.myriadrf.org/t/the-definitive-guide-on-loading-a-docker-ized-image-of-sdrangel/4434

I'm getting the following error:

sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
[sudo] password for shane: 
Hit:1 http://us.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 https://download.docker.com/linux/ubuntu focal InRelease                                                    
Get:3 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]                                        
Get:4 http://security.ubuntu.com/ubuntu focal-security InRelease [109 kB]                      
Ign:5 http://ppa.launchpad.net/szechyjs/dsd/ubuntu focal InRelease                        
Get:6 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]                              
Err:7 http://ppa.launchpad.net/szechyjs/dsd/ubuntu focal Release                                          
  404  Not Found [IP: 91.189.95.85 80]
Get:8 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 DEP-11 Metadata [264 kB]
Get:9 http://us.archive.ubuntu.com/ubuntu focal-updates/universe amd64 DEP-11 Metadata [303 kB]
Get:10 http://us.archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 DEP-11 Metadata [2,468 B]
Get:11 http://us.archive.ubuntu.com/ubuntu focal-backports/universe amd64 DEP-11 Metadata [1,768 B]
Get:12 http://security.ubuntu.com/ubuntu focal-security/main amd64 DEP-11 Metadata [24.3 kB]       
Get:13 http://security.ubuntu.com/ubuntu focal-security/universe amd64 DEP-11 Metadata [58.2 kB]
Reading package lists... Done               
E: The repository 'http://ppa.launchpad.net/szechyjs/dsd/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Regards,
Shane

**Comment by playaspec** [comment]
Pro tip: Edit whichever apt.source that points to the missing repo and change it from focal to xenial. The 18.04 PPA works just the same.

**Comment by francisuk1989** [comment]
There are two forks of DSD that i know of, One of them are in Ubuntu repos (none PPAs) but only DMR/D-STAR/YSF/DPMR is working is called dsdcc https://github.com/f4exb/dsdcc and can be installed from Ubuntu or Debian easy with
```
sudo apt-get update
sudo apt-get install dsdcc

There is also a guide on how to compile DSD itself here https://www.george-smart.co.uk/scrapbook/digital_speech_decoder/ but if you wont to easy route then dsdcc is in Repos.

**Comment by szechyjs** [comment]
I forgot to reply a few months ago, I updated the ppa to publish 20.04/focal packages.

https://launchpad.net/~szechyjs/+archive/ubuntu/dsd

**Comment by francisuk1989** [comment]
Can you make this possible for 22.04 LTS @szechyjs as this version wil be supported till  2027-04-21
