### ISSUE TITLE
Strange Audio Output

### ISSUE THREAD

**Issue by colbiedison** [szechyjs/dsd#123]
I've found one DMR frequency which occasionally contains voice, but when decoded with DSD, the audio is unintelligible.
Plenty of other frequencies work fine.
Sample of DSD output while receiving voice:
```
Sync:  +DMR       o:   24 mod: GFSK g: 9.658600 inlvl: 68% [slot0]  slot1   Slot idle    
Sync:  +DMR       o:   24 mod: GFSK g: 9.658600 inlvl: 70%  slot0  [slot1]  DATA Header  
Sync:  +DMR       o:   24 mod: GFSK g: 9.658600 inlvl: 69% [slot0]  slot1   Slot idle    
Sync:  +DMR       o:   24 mod: C4FM g: 9.658600 inlvl: 65%  slot0  [SLOT1]  VOICE e:==================R====
Sync:  +DMR       o:   24 mod: GFSK g: 3.876159 inlvl: 60%  slot0  [SLOT1]  VOICE e:======================
Sync:  +DMR       o:   24 mod: GFSK g: 3.876159 inlvl: 61%  slot0  [SLOT1]  VOICE e:====================R=====
Sync:  +DMR       o:   24 mod: C4FM g: 6.961025 inlvl: 63%  slot0  [SLOT1]  VOICE e:================
Sync:  +DMR       o:   24 mod: GFSK g: 15.631644 inlvl: 63%  slot0  [SLOT1]  VOICE e:=====================
Sync:  +DMR       o:   24 mod: GFSK g: 3.391137 inlvl: 61%  slot0  [SLOT1]  VOICE e:=========================R====R=====R
Sync:  +DMR       o:   24 mod: GFSK g: 3.391137 inlvl: 64%  slot0  [SLOT1]  VOICE e:======R=============R==============
Sync:  +DMR       o:   24 mod: GFSK g: 3.150008 inlvl: 63%  slot0  [SLOT1]  VOICE e:==================
Sync:  +DMR       o:   24 mod: C4FM g: 3.828855 inlvl: 64%  slot0  [slot1]  TLC          
Sync:  +DMR       o:   24 mod: C4FM g: 3.828855 inlvl: 65% [slot0]  slot1   Slot idle    
Sync:  +DMR       o:   24 mod: C4FM g: 3.828855 inlvl: 61%  slot0  [slot1]  TLC          
Sync:  +DMR       o:   24 mod: GFSK g: 3.828855 inlvl: 65% [slot0]  slot1   Slot idle    
```
A bunch of output audio:
[garbled_dmr.wav](https://cdn.discordapp.com/attachments/937427978953039902/991432821619052774/garbled_dmr.wav)

**System Information:**
OS: Arch Linux x86_64
Digital Speech Decoder 1.7.0-dev (build:v1.6.0-96-g59423fa)
mbelib version 1.3.0
libsndfile 1.1.0-2
itpp 4.3.1-1

**Comment by lwvmobile** [comment]
Can you submit a sample of the raw signal audio and not the decoded audio?

**Comment by colbiedison** [comment]
[Here you go.](https://cdn.discordapp.com/attachments/937427978953039902/991438054491443300/audio_152292500Hz_15-17-24_28-06-2022.wav)
Voice starts after about 30 seconds.

**Comment by lwvmobile** [comment]
Thanks. Its an encrypted transmission using RC4. That's why it sounds garbled.

16:31:41 Sync: +DMR  [slot1]  slot2  | Color Code=01 | (CRC OK ) | VOICE LC Header  
 Slot 1   TGT=3000  SRC=50003  Encrypted TXI Call  
16:31:42 Sync: +DMR   slot1  [slot2] | Color Code=01 | (CRC OK ) | Slot idle    
16:31:42 Sync: +DMR   slot1  [slot2] | Color Code=01 | (CRC OK ) | Slot idle    
16:31:42 Sync: +DMR  [slot1]  slot2  | Color Code=01 | (CRC OK ) | PI Header     
 Slot 1 DMR PI Header ALG ID: 0x21 KEY ID: 0x01 MI: 0xD8BF3EA0

**Comment by colbiedison** [comment]
Oh, interesting. Thanks!

**Comment by lwvmobile** [comment]
No problem, I'm also getting tons of errors in the signal as well, must be a noisy or faint signal, getting tons and tons of errors and having a hard time staying synced on it. Listening to in over the speakers make it sound like a lot of static as well.
