### ISSUE TITLE
DSD needs to be modified to work on OS X since no /dev/audio device is present

### ISSUE THREAD

**Issue by grempe** [szechyjs/dsd#2]
As referenced in the following closed pull request DSD apparently needs to be modified to work on OS X.

https://github.com/szechyjs/dsd/pull/1

See also the FAQ section at the bottom of:
http://wiki.radioreference.com/index.php/Digital_Speech_Decoder_(software_package)

I am re-opening this as a separate issue since the cmake change that was the subject of the previously mentioned pull request was merged in and closed without addressing the /dev/audio issue.

I have a homebrew formula pull request ready to go which compiles and installs both DSD and mbelib with a one line 'brew install dsd' on OS X.  I am reluctant to submit this pull request until I can test DSD locally with a sample file (e.g. a mototrbo capture from the discriminator tap of a scanner). The pull request for mbelib formula has already been submitted:

https://github.com/mxcl/homebrew/pull/21792

I'd love to see this working on OS X so I can capture signals using OS X SDR software or a scanner with a discriminator tap and feed them to DSD for realtime playback.

**Comment by Awoogabrother** [comment]
Mine (mid-2010 MBP) doesn't work with Portaudio + DSD (which was working-ish with GQRX)  is giving me this /dev/audio error that sucks. Might have been something to do with me installing Cubicsdr and trying to get P25 through sunflower and wineskin DSD+. Which would you go for and how should proceed? Delete everything SDR related and start building again? 
Thanks

**Comment by ELLIOTTCABLE** [comment]
Yeah, same as @Awoogabrother — this doesn't seem to be working on my macOS Sierra:

```
> brew install git cmake libsndfile itpp portaudio
> brew install --HEAD mbelib
> brew install --HEAD dsd
> dsd
Digital Speech Decoder 1.7.0-dev (build:-128-NOTFOUND)
mbelib version 1.2.5
Error, couldn't open /dev/audio
```

Any further steps I can attempt?

**Comment by nivex** [comment]
Run `dsd -a` to list the available Portaudio devices. Find the number of the device that matches your output and invoke with `dsd -o pa:6 ...` (having chosen `device #6` as my example).

**Comment by ELLIOTTCABLE** [comment]
@nivex strangely, that … gives precisely the same error? very unexpectedly?

```
> dsd -o pa:1
Digital Speech Decoder 1.7.0-dev (build:-128-NOTFOUND)
mbelib version 1.2.5
Initializing portaudio.
Using portaudio device 1.
Name                        = Built-in Line Output
Audio Out Device: pa:1
Error, couldn't open /dev/audio
```

**Comment by nivex** [comment]
Yep, that's a bug alright! Sorry, I got nothin' else :(

**Comment by szechyjs** [comment]
This is not a bug. You haven't specified an input. The default input is /dev/audio. Select an input device such as `-i pa:0` or `-i -` to pipe from stdin.

https://github.com/szechyjs/dsd/wiki/Operation#inputoutput-options

**Comment by nivex** [comment]
*facepalm* right, sorry. I've got my stuff scripted up that I haven't touched bare dsd in awhile.

**Comment by Awoogabrother** [comment]
The -i  -0 stuff ( just random variables ) are definitely buggy on OSX. I
guess you should expect it given the complexity of what it's doing. But for
example
I could get DSD+ working with GQRX over my laptop speakers --- but for the
life of me I could not get it going through my headphone jack🤔 If anyone
works out what port that is in DSD+ please let me know!  😂

**Comment by rd0fun** [comment]
So I have CubicSDR working perfectly on MacOS Catalina, and I have DSD compiled and running with portaudio.h. 
How does one link zCubicSDR to DSD? This didn't work. What am I doing wrong?

$ dsd -o pa:1 
Digital Speech Decoder 1.7.0-dev (build:HEAD-HASH-NOTFOUND)
mbelib version 1.3.0
Initializing portaudio.
Using portaudio device 1.
Name                        = MacBook Pro Speakers
Audio Out Device: pa:1
Error, couldn't open /dev/audio
$

**Comment by nivex** [comment]
@rd0fun You've done the same thing as discussed in a comment above:
> You haven't specified an input. The default input is /dev/audio. Select an input device such as `-i pa:0` or `-i -` to pipe from stdin.
> 
> https://github.com/szechyjs/dsd/wiki/Operation#inputoutput-options
