### ISSUE TITLE
newb dsd

### ISSUE THREAD

**Issue by 401402** [szechyjs/dsd#50]
please email me  ron_cathers@hotmail.com
using windows 8.1 hp laptop
i cant figure out how to download dsd 1.6 onto my compputer

**Comment by szechyjs** [comment]
dsd can only be compiled in a unix environment. you need to use cygwin to compile on windows. or download a previously compiled binary.

http://wiki.radioreference.com/index.php/Digital_Speech_Decoder_%28software_package%29#Help_Page_for_Windows
