### ISSUE TITLE
dsd - .raw and .rawiq files sample format

### ISSUE THREAD

**Issue by jonwhitee** [szechyjs/dsd#59]
Hi jared,

love your dsd its works great,
i'm a student, and i want to know more about the samples in .raw and .rawiq files,
i want to open them in matlab and see the signals, i know that the file data look like this 48k/16bits/mono/pcm, but how one sample of 16bit looks like? and what it presents?

Thank you.

**Comment by jonwhitee** [comment]
up

**Comment by EdFuentetaja** [comment]
The .rawiq files are I/Q samples. Here you can get some information on what they represent: http://whiteboard.ping.se/SDR/IQ
The format is PCM 16bits, with two alternating channels, one I, the other Q.
Those files can be read from Octave (Matlab open-source clone) with something like this:
'
fid = fopen("path to .rawiq file");
IQ = fread(fid, Inf, "int16", arch="ieee-le");
fclose(fid);

MIQ = reshape(IQ, 2, length(IQ)/2);
I = MIQ(1,:);
Q = MIQ(2,:);

subplot(2,1,1);
plot(I);
subplot(2,1,2);
plot(Q);
'

.raw files contain the baseband FM-demodulated IQ data. Its format is PCM 16bits, mono. That's the input to the DSD library.

Good luck!

**Comment by bilbolodz** [comment]
Could someone tell me (using simple "command example") how to use files from dsd-samples directory and dsd to decode and get "audio signal". I'm trying to start with dsd and decoding live signals but got some issues so I wan't to test it first with sample files.
