### ISSUE TITLE
Digital Speech Decoder (software download package)

### ISSUE THREAD

**Issue by VE3WZW** [szechyjs/dsd#67]
I am looking for the best source for the latest version of the Digital Speech Decoder (software package) for windows.  Any suggestions ?

**Comment by szechyjs** [comment]
You probably are looking for [DSDPlus](https://www.dsdplus.com/) which is the Windows fork of this project.

**Comment by HAMradioCanada** [comment]
You can download the latest version of dsd+ at this site which is always kept up to date http://www.dsdplus.com/
