### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by marcoblacks** [szechyjs/dsd#68]
Hi, after installing dsd-master, mbelib, libsndfile, it++ on ubuntu 14.04,  itried to run dsd but this error occur:
error while loading shared libraries: libmbe.so.1: cannot open shared object file : no such file or directory.
Please help!

**Comment by nivex** [comment]
You may need to run `ldconfig` to make the library usable after install.

**Comment by marcoblacks** [comment]
Thanks, i resolved moving  from local/usr/lib into  /usr/lib, but now i stopped for another error:
coudn't open /dev/audio!
I also tryed run dsd -i /dev/snd but same problem...

**Comment by szechyjs** [comment]
on modern linux systems you should use port audio.

`dsd -a` will list available devices.

then use the listed devices for input/output `dsd -i pa:0 -o pa:1`

**Comment by marcoblacks** [comment]
Thanks Szechyjs!! I resolved using exactly your command.
Now all seems work well but: dsd start, and all information are displayed, VOICE CALL, etc.. but i can't hear any voice audio output, i tryed also with my Mototrbo radio in clear mode...
No way, i choose with ubuntu sound application another output device (i installed 2 audio sound card), but is the same...
The only strange information i got after running dsd is : 

dsd digital speech decode 1.7.0-dev (BUILD:HEAD-HASH-NOTFOUND)

why BUILD: HEAD-HASH_NOTFOUND? are there some problem with the speech decoding routine?

Thanks a lots everybody!
Marco

**Comment by marcoblacks** [comment]
Just trying the option -w drmtestfile.wav, and dsd can write the decoded wavefile correctly...
So..?

**Comment by riceml** [comment]
hi~~ i also encountered the same problem......
$ dsd
Digital Speech Decoder 1.7.0-dev (build:v1.6.0-86-g7ee04e5)
mbelib version 1.3.0
Error, couldn't open /dev/audio
$ dsd -a
Digital Speech Decoder 1.7.0-dev (build:v1.6.0-86-g7ee04e5)
mbelib version 1.3.0
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.1.2/work/alsa-lib-1.1.2/src/pcm/pcm.c:2450:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.1.2/work/alsa-lib-1.1.2/src/pcm/pcm.c:2450:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.1.2/work/alsa-lib-1.1.2/src/pcm/pcm.c:2450:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.1.2/work/alsa-lib-1.1.2/src/pcm/pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.1.2/work/alsa-lib-1.1.2/src/pcm/pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.1.2/work/alsa-lib-1.1.2/src/pcm/pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.1.2/work/alsa-lib-1.1.2/src/pcm/pcm_route.c:867:(find_matching_chmap) Found no matching channel map
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed

PortAudio version number = 1899
PortAudio version text = 'PortAudio V19-devel (built Oct 18 2017 20:59:45)'
Number of devices = 10
--------------------------------------- device #0
Name                        = HDA Intel: ALC662 rev1 Analog (hw:0,0)
Host API                    = ALSA
Max inputs = 2, Max outputs = 2
Default sample rate         = 44100.00
--------------------------------------- device #1
Name                        = HDA Intel: ALC662 rev1 Alt Analog (hw:0,2)
Host API                    = ALSA
Max inputs = 2, Max outputs = 0
Default sample rate         = 44100.00
--------------------------------------- device #2
Name                        = sysdefault
Host API                    = ALSA
Max inputs = 128, Max outputs = 128
Default sample rate         = 48000.00
--------------------------------------- device #3
Name                        = front
Host API                    = ALSA
Max inputs = 0, Max outputs = 2
Default sample rate         = 44100.00
--------------------------------------- device #4
Name                        = surround40
Host API                    = ALSA
Max inputs = 0, Max outputs = 2
Default sample rate         = 44100.00
--------------------------------------- device #5
Name                        = surround51
Host API                    = ALSA
Max inputs = 0, Max outputs = 2
Default sample rate         = 44100.00
--------------------------------------- device #6
Name                        = surround71
Host API                    = ALSA
Max inputs = 0, Max outputs = 2
Default sample rate         = 44100.00
--------------------------------------- device #7
Name                        = pulse
Host API                    = ALSA
Max inputs = 32, Max outputs = 32
Default sample rate         = 44100.00
--------------------------------------- device #8
Name                        = dmix
Host API                    = ALSA
Max inputs = 0, Max outputs = 2
Default sample rate         = 48000.00
--------------------------------------- device #9
[ Default Input, Default Output ]
Name                        = default
Host API                    = ALSA
Max inputs = 32, Max outputs = 32
Default sample rate         = 44100.00
----------------------------------------------
$ dsd -i pa:1 -o pa:0
Digital Speech Decoder 1.7.0-dev (build:v1.6.0-86-g7ee04e5)
mbelib version 1.3.0
Initializing portaudio.
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.1.2/work/alsa-lib-1.1.2/src/pcm/pcm.c:2450:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.1.2/work/alsa-lib-1.1.2/src/pcm/pcm.c:2450:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.1.2/work/alsa-lib-1.1.2/src/pcm/pcm.c:2450:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.1.2/work/alsa-lib-1.1.2/src/pcm/pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.1.2/work/alsa-lib-1.1.2/src/pcm/pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.1.2/work/alsa-lib-1.1.2/src/pcm/pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.1.2/work/alsa-lib-1.1.2/src/pcm/pcm_route.c:867:(find_matching_chmap) Found no matching channel map
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
Using portaudio device 0.
Name                        = HDA Intel: ALC662 rev1 Analog (hw:0,0)
Expression 'paInvalidSampleRate' failed in '/var/tmp/portage/media-libs/portaudio-19_pre20140130/work/portaudio/src/hostapi/alsa/pa_linux_alsa.c', line: 2043
Expression 'PaAlsaStreamComponent_InitialConfigure( &self->playback, outParams, self->primeBuffers, hwParamsPlayback, &realSr )' failed in '/var/tmp/portage/media-libs/portaudio-19_pre20140130/work/portaudio/src/hostapi/alsa/pa_linux_alsa.c', line: 2717
Expression 'PaAlsaStream_Configure( stream, inputParameters, outputParameters, sampleRate, framesPerBuffer, &inputLatency, &outputLatency, &hostBufferSizeMode )' failed in '/var/tmp/portage/media-libs/portaudio-19_pre20140130/work/portaudio/src/hostapi/alsa/pa_linux_alsa.c', line: 2838
An error occured while initializing a portaudio stream
Error number: -9997
Error message: Invalid sample rate

~~~feeling that the brain is blank,please pass by a friend to help solve,Thanks....

**Comment by szechyjs** [comment]
@riceml this is a known issue with some chipsets #42

**Comment by szechyjs** [comment]
@marcoblacks the `BUILD: HEAD-HASH_NOTFOUND` is a result of not building from a git clone, those values are only populated by git. It does not affect anything other than displaying version information.

Closing this issue as its getting off topic.

**Comment by riceml** [comment]
@szechyjs Is there any solution?

**Comment by szechyjs** [comment]
@riceml dsd has a hardcoded sample rate of 48k. As shown in your output your devices have a 44.1k sample rate. Pull Requests to fix this issue welcomed, sample rate would need to be adjusted based on selected device.
