### ISSUE TITLE
CMake error

### ISSUE THREAD

**Issue by postmodern** [szechyjs/dsd#69]
DSD commit: 7ee04e58c5b18d42fbb2b2138246f7d6f380b6fc
itpp version: 4.3.1
mbelib version: 1.3.0
OS: Fedora Linux 25 [x86-64]
CMake version: 3.8.0

Steps to Reproduce:

    mkdir build
    cd build
    cmake ..
    -- Found LibSndFile: /usr/lib64/libsndfile.so
    -- Found LibMbe: /usr/local/lib/libmbe.so
    -- Found ITPP: /usr/local/lib/libitpp.so
    -- Checking for module 'portaudio-2.0'
    --   Found portaudio-2.0, version 19
    CMake Warning (dev) at test/CMakeLists.txt:13 (add_custom_target):
      Policy CMP0037 is not set: Target names should not be reserved and should
      match a validity pattern.  Run "cmake --help-policy CMP0037" for policy
      details.  Use the cmake_policy command to set the policy and suppress this
      warning.

      The target name "test" is reserved or not valid for certain CMake features,
      such as generator expressions, and may result in undefined behavior.
    This warning is for project developers.  Use -Wno-dev to suppress it.

    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/postmodern/src/dsd/build

**Comment by orsty3001** [comment]
I have the same error on Mint 18.1 64 bit.

**Comment by szechyjs** [comment]
Not an error, just a warning. One of theses days I'll change the name of the test program (or someone can submit a PR).
