### ISSUE TITLE
Make Error

### ISSUE THREAD

**Issue by orsty3001** [szechyjs/dsd#70]
I'm getting this when trying to run make after cmake. 

CMakeFiles/dsd.dir/src/dsd_mbe.c.o: In function `playMbeFiles':
dsd_mbe.c:(.text+0x2dd): undefined reference to `mbe_processAmbe2450Dataf'
CMakeFiles/dsd.dir/src/dsd_mbe.c.o: In function `processMbeFrame':
dsd_mbe.c:(.text+0x6be): undefined reference to `mbe_processAmbe3600x2400Framef'
dsd_mbe.c:(.text+0x78f): undefined reference to `mbe_processAmbe3600x2450Framef'
collect2: error: ld returned 1 exit status
CMakeFiles/dsd.dir/build.make:981: recipe for target 'dsd' failed
make[2]: *** [dsd] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/dsd.dir/all' failed
make[1]: *** [CMakeFiles/dsd.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

It's on a system running Mint 18.1 64 bit.

**Comment by szechyjs** [comment]
Do you have [mbelib](https://github.com/szechyjs/mbelib) installed?

**Comment by androoski** [comment]
Hello,

I seem to be experiencing the same issue on make and would appreciate any pointers to resolving this.  

"[ 70%] Linking CXX executable dsd
CMakeFiles/dsd.dir/src/dsd_mbe.c.o: In function `playMbeFiles':
dsd_mbe.c:(.text+0x2dd): undefined reference to `mbe_processAmbe2450Dataf'
CMakeFiles/dsd.dir/src/dsd_mbe.c.o: In function `processMbeFrame':
dsd_mbe.c:(.text+0x6be): undefined reference to `mbe_processAmbe3600x2400Framef'
dsd_mbe.c:(.text+0x78f): undefined reference to `mbe_processAmbe3600x2450Framef'
collect2: error: ld returned 1 exit status
CMakeFiles/dsd.dir/build.make:981: recipe for target 'dsd' failed
make[2]: *** [dsd] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/dsd.dir/all' failed
make[1]: *** [CMakeFiles/dsd.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
"

 i do have mbelib installed

~/radio/mbelib/build# make install
[ 50%] Built target mbe-static
[100%] Built target mbe-shared
Install the project...
-- Install configuration: ""
-- Up-to-date: /usr/local/lib/libmbe.a
-- Up-to-date: /usr/local/lib/libmbe.so.1.0
-- Up-to-date: /usr/local/lib/libmbe.so.1
-- Up-to-date: /usr/local/lib/libmbe.so
-- Up-to-date: /usr/local/include/mbelib.h

kernel: Linux xxx 4.4.0-92-generic #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

ubuntu release:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

Scanning dependencies of target dsd
[  1%] Building C object CMakeFiles/dsd.dir/src/dsd_main.c.o
[  3%] Building C object CMakeFiles/dsd.dir/src/p25p1_ldu2.c.o
[  5%] Building C object CMakeFiles/dsd.dir/src/dstar.c.o
[  7%] Building C object CMakeFiles/dsd.dir/src/dsd_upsample.c.o
[  9%] Building C object CMakeFiles/dsd.dir/src/dsd_filters.c.o
[ 11%] Building C object CMakeFiles/dsd.dir/src/dsd_frame.c.o
[ 13%] Building C object CMakeFiles/dsd.dir/src/dsd_frame_sync.c.o
[ 15%] Building C object CMakeFiles/dsd.dir/src/dstar_header.c.o
[ 17%] Building C object CMakeFiles/dsd.dir/src/nxdn_voice.c.o
[ 19%] Building C object CMakeFiles/dsd.dir/src/dsd_dibit.c.o
[ 21%] Building C object CMakeFiles/dsd.dir/src/p25p1_hdu.c.o
[ 23%] Building C object CMakeFiles/dsd.dir/src/dmr_data.c.o
[ 25%] Building C object CMakeFiles/dsd.dir/src/x2tdma_voice.c.o
[ 27%] Building C object CMakeFiles/dsd.dir/src/provoice.c.o
[ 29%] Building C object CMakeFiles/dsd.dir/src/x2tdma_data.c.o
[ 31%] Building C object CMakeFiles/dsd.dir/src/dsd_file.c.o
[ 33%] Building C object CMakeFiles/dsd.dir/src/p25_lcw.c.o
[ 35%] Building C object CMakeFiles/dsd.dir/src/dsd_mbe.c.o
/home/andy/radio/dsd/src/dsd_mbe.c: In function ‘playMbeFiles’:
/home/andy/radio/dsd/src/dsd_mbe.c:54:15: warning: implicit declaration of function ‘mbe_processAmbe2450Dataf’ [-Wimplicit-function-declaration]
               mbe_processAmbe2450Dataf (state->audio_out_temp_buf, &state->errs, &state->errs2, state->err_str, ambe_d, state->cur_mp, state->prev_mp, state->pre
               ^
/home/andy/radio/dsd/src/dsd_mbe.c: In function ‘processMbeFrame’:
/home/andy/radio/dsd/src/dsd_mbe.c:110:7: warning: implicit declaration of function ‘mbe_processAmbe3600x2400Framef’ [-Wimplicit-function-declaration]
       mbe_processAmbe3600x2400Framef (state->audio_out_temp_buf, &state->errs, &state->errs2, state->err_str, ambe_fr, ambe_d, state->cur_mp, state->prev_mp, sta
       ^
/home/andy/radio/dsd/src/dsd_mbe.c:118:7: warning: implicit declaration of function ‘mbe_processAmbe3600x2450Framef’ [-Wimplicit-function-declaration]
       mbe_processAmbe3600x2450Framef (state->audio_out_temp_buf, &state->errs, &state->errs2, state->err_str, ambe_fr, ambe_d, state->cur_mp, state->prev_mp, sta
       ^
[ 37%] Building C object CMakeFiles/dsd.dir/src/nxdn96.c.o
[ 39%] Building C object CMakeFiles/dsd.dir/src/dmr_voice.c.o
[ 41%] Building C object CMakeFiles/dsd.dir/src/pa_devs.c.o
[ 43%] Building C object CMakeFiles/dsd.dir/src/p25p1_tdu.c.o
[ 45%] Building C object CMakeFiles/dsd.dir/src/dsd_serial.c.o
[ 47%] Building C object CMakeFiles/dsd.dir/src/p25p1_tdulc.c.o
[ 49%] Building C object CMakeFiles/dsd.dir/src/p25p1_heuristics.c.o
[ 50%] Building C object CMakeFiles/dsd.dir/src/dsd_audio.c.o
[ 52%] Building C object CMakeFiles/dsd.dir/src/dsd_symbol.c.o
[ 54%] Building C object CMakeFiles/dsd.dir/src/p25p1_ldu1.c.o
[ 56%] Building C object CMakeFiles/dsd.dir/src/p25p1_ldu.c.o
[ 58%] Building C object CMakeFiles/dsd.dir/src/nxdn_data.c.o
[ 60%] Building CXX object CMakeFiles/dsd.dir/src/p25p1_check_ldu.cpp.o
[ 62%] Building CXX object CMakeFiles/dsd.dir/src/p25p1_check_hdu.cpp.o
[ 64%] Building CXX object CMakeFiles/dsd.dir/src/p25p1_check_nid.cpp.o
[ 66%] Building CXX object CMakeFiles/dsd.dir/src/Hamming.cpp.o
[ 68%] Building C object CMakeFiles/dsd.dir/git_ver.c.o
[ 70%] Linking CXX executable dsd
CMakeFiles/dsd.dir/src/dsd_mbe.c.o: In function `playMbeFiles':
dsd_mbe.c:(.text+0x2dd): undefined reference to `mbe_processAmbe2450Dataf'
CMakeFiles/dsd.dir/src/dsd_mbe.c.o: In function `processMbeFrame':
dsd_mbe.c:(.text+0x6be): undefined reference to `mbe_processAmbe3600x2400Framef'
dsd_mbe.c:(.text+0x78f): undefined reference to `mbe_processAmbe3600x2450Framef'
collect2: error: ld returned 1 exit status
CMakeFiles/dsd.dir/build.make:981: recipe for target 'dsd' failed
make[2]: *** [dsd] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/dsd.dir/all' failed
make[1]: *** [CMakeFiles/dsd.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Appreciatively,
-A

**Comment by szechyjs** [comment]
Set `CMAKE_VERBOSE_MAKEFILE` to ON either through `ccmake` or with `cmake -DCMAKE_VERBOSE_MAKEFILE=ON ..`, and post the output related to linking. It should look something like this:

```
[ 70%] Linking CXX executable dsd
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/dsd.dir/link.txt --verbose=1
/usr/bin/c++      CMakeFiles/dsd.dir/src/p25p1_ldu.c.o CMakeFiles/dsd.dir/src/dsd_filters.c.o CMakeFiles/dsd.dir/src/p25p1_ldu2.c.o CMakeFiles/dsd.dir/src/x2tdma_voice.c.o CMakeFiles/dsd.dir/src/dstar.c.o CMakeFiles/dsd.dir/src/nxdn_voice.c.o CMakeFiles/dsd.dir/src/x2tdma_data.c.o CMakeFiles/dsd.dir/src/dstar_header.c.o CMakeFiles/dsd.dir/src/dmr_data.c.o CMakeFiles/dsd.dir/src/dsd_main.c.o CMakeFiles/dsd.dir/src/p25p1_tdu.c.o CMakeFiles/dsd.dir/src/p25p1_ldu1.c.o CMakeFiles/dsd.dir/src/dsd_symbol.c.o CMakeFiles/dsd.dir/src/p25p1_hdu.c.o CMakeFiles/dsd.dir/src/provoice.c.o CMakeFiles/dsd.dir/src/dsd_frame_sync.c.o CMakeFiles/dsd.dir/src/dsd_upsample.c.o CMakeFiles/dsd.dir/src/nxdn96.c.o CMakeFiles/dsd.dir/src/p25_lcw.c.o CMakeFiles/dsd.dir/src/dsd_audio.c.o CMakeFiles/dsd.dir/src/dsd_mbe.c.o CMakeFiles/dsd.dir/src/dsd_frame.c.o CMakeFiles/dsd.dir/src/nxdn_data.c.o CMakeFiles/dsd.dir/src/dmr_voice.c.o CMakeFiles/dsd.dir/src/p25p1_heuristics.c.o CMakeFiles/dsd.dir/src/p25p1_tdulc.c.o CMakeFiles/dsd.dir/src/dsd_dibit.c.o CMakeFiles/dsd.dir/src/pa_devs.c.o CMakeFiles/dsd.dir/src/dsd_file.c.o CMakeFiles/dsd.dir/src/dsd_serial.c.o CMakeFiles/dsd.dir/src/p25p1_check_nid.cpp.o CMakeFiles/dsd.dir/src/Hamming.cpp.o CMakeFiles/dsd.dir/src/p25p1_check_hdu.cpp.o CMakeFiles/dsd.dir/src/p25p1_check_ldu.cpp.o CMakeFiles/dsd.dir/git_ver.c.o  -o dsd -rdynamic /usr/local/lib/libmbe.so -lsndfile /usr/local/lib/libitpp.so -lportaudio -lasound -lm -lpthread -Wl,-rpath,/usr/local/lib:
make[2]: Leaving directory '/home/jared/code/dsd/build'
[ 70%] Built target dsd
```

**Comment by androoski** [comment]
Hello,

with cmake -DCMAKE_VERBOSE_MAKEFILE=ON  set, on make

```
[ 70%] Linking CXX executable dsd
/usr/bin/cmake -E cmake_link_script CMakeFiles/dsd.dir/link.txt --verbose=1
/usr/bin/c++      CMakeFiles/dsd.dir/src/dsd_main.c.o CMakeFiles/dsd.dir/src/p25p1_ldu2.c.o CMakeFiles/dsd.dir/src/dstar.c.o CMakeFiles/dsd.dir/src/dsd_upsample.c.o CMakeFiles/dsd.dir/src/dsd_filters.c.o CMakeFiles/dsd.dir/src/dsd_frame.c.o CMakeFiles/dsd.dir/src/dsd_frame_sync.c.o CMakeFiles/dsd.dir/src/dstar_header.c.o CMakeFiles/dsd.dir/src/nxdn_voice.c.o CMakeFiles/dsd.dir/src/dsd_dibit.c.o CMakeFiles/dsd.dir/src/p25p1_hdu.c.o CMakeFiles/dsd.dir/src/dmr_data.c.o CMakeFiles/dsd.dir/src/x2tdma_voice.c.o CMakeFiles/dsd.dir/src/provoice.c.o CMakeFiles/dsd.dir/src/x2tdma_data.c.o CMakeFiles/dsd.dir/src/dsd_file.c.o CMakeFiles/dsd.dir/src/p25_lcw.c.o CMakeFiles/dsd.dir/src/dsd_mbe.c.o CMakeFiles/dsd.dir/src/nxdn96.c.o CMakeFiles/dsd.dir/src/dmr_voice.c.o CMakeFiles/dsd.dir/src/pa_devs.c.o CMakeFiles/dsd.dir/src/p25p1_tdu.c.o CMakeFiles/dsd.dir/src/dsd_serial.c.o CMakeFiles/dsd.dir/src/p25p1_tdulc.c.o CMakeFiles/dsd.dir/src/p25p1_heuristics.c.o CMakeFiles/dsd.dir/src/dsd_audio.c.o CMakeFiles/dsd.dir/src/dsd_symbol.c.o CMakeFiles/dsd.dir/src/p25p1_ldu1.c.o CMakeFiles/dsd.dir/src/p25p1_ldu.c.o CMakeFiles/dsd.dir/src/nxdn_data.c.o CMakeFiles/dsd.dir/src/p25p1_check_ldu.cpp.o CMakeFiles/dsd.dir/src/p25p1_check_hdu.cpp.o CMakeFiles/dsd.dir/src/p25p1_check_nid.cpp.o CMakeFiles/dsd.dir/src/Hamming.cpp.o CMakeFiles/dsd.dir/git_ver.c.o  -o dsd -rdynamic /usr/local/lib/libmbe.so -lsndfile /usr/local/lib/libitpp.so -lportaudio -lasound -lm -lpthread -Wl,-rpath,/usr/local/lib: 
CMakeFiles/dsd.dir/src/dsd_mbe.c.o: In function `playMbeFiles':
dsd_mbe.c:(.text+0x2dd): undefined reference to `mbe_processAmbe2450Dataf'
CMakeFiles/dsd.dir/src/dsd_mbe.c.o: In function `processMbeFrame':
dsd_mbe.c:(.text+0x6be): undefined reference to `mbe_processAmbe3600x2400Framef'
dsd_mbe.c:(.text+0x78f): undefined reference to `mbe_processAmbe3600x2450Framef'
collect2: error: ld returned 1 exit status
CMakeFiles/dsd.dir/build.make:984: recipe for target 'dsd' failed
make[2]: *** [dsd] Error 1
make[2]: Leaving directory '/home/andy/radio/dsd'
CMakeFiles/Makefile2:70: recipe for target 'CMakeFiles/dsd.dir/all' failed
make[1]: *** [CMakeFiles/dsd.dir/all] Error 2
make[1]: Leaving directory '/home/andy/radio/dsd'
Makefile:130: recipe for target 'all' failed
make: *** [all] Error 2

```


Thanks for the help.
-A

**Comment by szechyjs** [comment]
`-rdynamic /usr/local/lib/libmbe.so` was in the link line so I'm guessing it has to be something wrong with your mbelib build/install.

Do you get any output from?

```sh
objdump -T /usr/local/lib/libmbe.so | grep mbe_processAmbe2450Dataf
```

If not how about the static library?

```sh
nm -g /usr/local/lib/libmbe.a | grep mbe_processAmbe2450Dataf
```

**Comment by androoski** [comment]
Hi Jared,

The output to those commands was nil so I started from scratch by rebuilding libmbe.   DSD built with no issues on the next attempt.  doh.

Thanks so much for the assist and the quality code.

Cheers,
-A
