### ISSUE TITLE
Chopped audio on Raspberry

### ISSUE THREAD

**Issue by sh123** [szechyjs/dsd#72]
Tried to run DSD on Raspberry. 

+DMR messages are printed out to console, seems to be able to decode.

But when audio is recorded to .wav file it is chopped, not possible to understand a single word. 

Tried to use mbuffer thinking that pipe is not large enough to hold all the data when dsd is not able to consume fast enough, but it still the same.

Is ARM architecture supported by DSD/MBElib or is Raspberry not powerful enough to run it? 

Anyone tried to use DSD successfully on Raspberry or other ARM device?

**Comment by sh123** [comment]
Seems that all is good, ARM device was just too weak to decode voice fast enough, by playing a little big more with mbuffer managed to get it working with this command:

`
# rtl_fm -F1 -o4 -g 30 -f <freq>-M fm -p "-89" -s 48k -A fast -l 0 -E deemp | mbuffer -c -m 50M | dsd -mg -v 10 -fr -i -  -w test.wav
`

**Comment by BrianG61UK** [comment]
Was this a Raspberry Pi V1, V2 or V3?

-- 

Brian Gregory.
bdgregory@gmail.com
www.Brian-Gregory.me.uk

**Comment by sh123** [comment]
It is V2, ARMv7
