### ISSUE TITLE
dsd

### ISSUE THREAD

**Issue by apptestmail** [szechyjs/dsd#78]
dears 
any one can help me with that issue 

Digital Speech Decoder 1.7.0-dev (build:v1.6.0-86-g7ee04e5)
mbelib version 1.3.0
Error, couldn't open /dev/audio

**Comment by apptestmail** [comment]
more details

Digital Speech Decoder 1.7.0-dev (build:v1.6.0-86-g7ee04e5)
mbelib version 1.3.0
Error, couldn't open /dev/audio
ioctl reset error 
ioctl speed error 
ioctl stereo error 
ioctl setfmt error 
Audio In/Out Device: /dev/audio

**Comment by szechyjs** [comment]
Please consult the documentation...

https://github.com/szechyjs/dsd/wiki/Operation#inputoutput-options
