### ISSUE TITLE
need help 

### ISSUE THREAD

**Issue by apptestmail** [szechyjs/dsd#80]
can any one help me ,and tell me how to fix that issue 
Sync:  +DMR       mod: QPSK inlvl:  1% [SLOT0]  slot1   VOICE e:=====R======R=======E=E========R====R====R============R=
Sync: (+DMR)      mod: C4FM inlvl: 12%  SLOT0  [slot1]  VOICE e:=======R====R====R==========R=======R====R====R=======E==T==E==T
Sync: no sync
Sync:  +DMR       mod: C4FM inlvl: 46%  slot0  [SLOT1]  VOICE e:======R=======R======R======R======E=================
Sync: (+DMR)      mod: C4FM inlvl: 23%  slot0  [SLOT1]  VOICE e:=====R============R=============R=============R========
Sync:  +DMR       mod: C4FM inlvl: 12%  slot0  [SLOT1]  VOICE e:====R=====R======R==========================R=====
Sync: (+DMR)      mod: C4FM inlvl:  6% [slot0]  SLOT1   VOICE e:====R=====R==============R==============R================R
Sync:  +DMR       mod: C4FM inlvl:  3% [SLOT0]  SLOT1   VOICE e:======R======R======R===================R======R====R=
Sync: (+DMR)      mod: GFSK inlvl:  2% [SLOT0]  SLOT1   VOICE e:===========R====R=====R====RM==========R==========R=============R====R=====R
Sync:  +DMR       mod: C4FM inlvl:  1% [SLOT0]  SLOT1   VOICE e:=============================R===E=======R
Sync: (+DMR)      mod: C4FM inlvl:  2% [SLOT0]  SLOT1   VOICE e:======R====R==============R==============R==========T====R
Sync: no sync
Sync:  +DMR       mod: GFSK inlvl:  1% [SLOT0]  slot1   VOICE e:===E====R=====R======E=====R=================
Sync: (+DMR)      mod: GFSK inlvl:  1% [SLOT0]  SLOT1   VOICE e:======T====R====R====R=========R====R====R=========R============R===
Sync: no sync
Sync:  +DMR       mod: QPSK inlvl:  1% [SLOT0]  slot1   VOICE e:=============E======R=======R=======R=======R====R
Sync: (+DMR)      mod: C4FM inlvl: 21%  SLOT0  [slot1]  VOICE e:========R=================R===E=======T==T==T==T==T==T==T
Sync:  +DMR       mod: C4FM inlvl: 11% [SLOT0]  slot1   VOICE e:==T==T==T==T==T==T==T==T==T====T==T==T==T==T==T
Sync: (+DMR)      mod: C4FM inlvl:  9%  SLOT0  [slot1]  VOICE e:==TT==T==T==T====T=T==T=T====T=T====R====T=T=T==T
 im use kali 
root@kali:~# uname -a
Linux kali 4.14.0-kali3-amd64 #1 SMP Debian 4.14.17-1kali1 (2018-02-16) x86_64 GNU/Linux

**Comment by szechyjs** [comment]
What is the issue?

**Comment by makerio90** [comment]
i don't know what the issue was but you inlvl looks to low
