### ISSUE TITLE
dsd cmake error help

### ISSUE THREAD

**Issue by riceml** [szechyjs/dsd#81]
#cd dsd
# mkdir build
# cd build
# cmake ..
-- The C compiler identification is GNU 6.4.0
-- The CXX compiler identification is GNU 6.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found LibSndFile: /usr/lib/libsndfile.so
CMake Error at cmake/FindLibMbe.cmake:18 (MESSAGE):
  Could not find mbe
Call Stack (most recent call first):
  CMakeLists.txt:10 (find_package)

**Comment by riceml** [comment]
Problem solved, request closed

**Comment by IZ3GAC** [comment]
Hi "riceml" can you tell me how you solved? I just have the same issue!! Thanks in advance.

**Comment by chancechen783** [comment]
Please install mbelib first, if you got the error message 'Could not find mbe'.
https://github.com/szechyjs/mbelib
