### ISSUE TITLE
No decode data in Linux DSD version

### ISSUE THREAD

**Issue by ziorick** [szechyjs/dsd#87]
Data in DMR was not decoded.

**Comment by szechyjs** [comment]
Please provide more details, what data are you referring to?

**Comment by ziorick** [comment]
> Please provide more details, what data are you referring to?

Sync:  +DMR       mod: GFSK inlvl: 32%  slot0  [slot1]  CSBK         
Sync:  +DMR       mod: GFSK inlvl: 32% [slot0]  slot1   CSBK         
Sync:  +DMR       mod: GFSK inlvl: 31%  slot0  [slot1]  CSBK         
Sync:  +DMR       mod: GFSK inlvl: 32% [slot0]  slot1   CSBK
...
Sync:  +DMR       mod: GFSK inlvl: 32%  slot0  [slot1]  RATE 3/4 DATA
Sync:  +DMR       mod: GFSK inlvl: 32% [slot0]  slot1   CSBK         
Sync:  +DMR       mod: GFSK inlvl: 32%  slot0  [slot1]  RATE 3/4 DATA
Sync:  +DMR       mod: GFSK inlvl: 32% [slot0]  slot1   CSBK         
Sync:  +DMR       mod: GFSK inlvl: 32%  slot0  [slot1]  RATE 3/4 DATA

The DATA contained...

**Comment by szechyjs** [comment]
Correct, we don't 'decode' the data frames, as it can be anything. If you want to see the raw data you can compile with the `DMR_DUMP` defined (in config.h).

**Comment by ziorick** [comment]
Ok... I'll try

Il dom 28 ott 2018, 16:08 Jared Szechy <notifications@github.com> ha
scritto:
